version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rahasia
      - DB_NAME=leftovers_db
      - JWT_SECRET=leftovers_super_secret_key
    depends_on:
      db:
        condition: service_healthy
    command: npm run dev

  api-backend:
    image: leftovers-api-api
    network_mode: "host"

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rahasia
      - MYSQL_DATABASE=leftovers_db
    volumes:
      # init.sql akan otomatis dijalankan saat database pertama kali dibuat
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db_data: